import { Inter, Jomhuria } from "next/font/google";
import Navbar from "../components/Navbar/Navbar";
import Footer from "../components/Footer/Footer";
import favicon from "../public/favicon.ico";

import SessionAuthProvider from "@/context/SessionAuthProvider";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
export const jomhuria = Jomhuria({
  subsets: ["latin"],
  weight: "400",
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <title>Kimey</title>
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <meta name="description" content="Generated by create next app" />
      <head>
        <link rel="icon" href={favicon.src} />
      </head>
      <body className={inter.className}>
        <Navbar />
        <SessionAuthProvider>{children}</SessionAuthProvider>
        <Footer />
      </body>
    </html>
  );
}
